#!/bin/sh
# Script that run a color test that shows you the contrast
# @Author: AlphaLawless

main() {
	cat <<- EOF
		[*] Want you color test?

		[*] Choose one -
		[1] Yes...
		[2] No...
	EOF

	read -p "[?] Select Option : "

	if [[ $REPLY == "1" ]]; then
		clear
		printf "          "
		for b in 0 1 2 3 4 5 6 7; do printf "  4${b}m "; done
		echo
		for f in "" 30 31 32 33 34 35 36 37; do
    			for s in "" "1;"; do
        			printf "%4sm" "${s}${f}"
        			printf " \033[%sm%s\033[0m" "$s$f" "gYw"
        			for b in 0 1 2 3 4 5 6 7; do
            				printf " \033[4%s;%sm%s\033[0m" "$b" "$s$f" " gYw "
        			done
        			echo
     			done
		done
		exit 1
	elif [[ $REPLY == "2" ]]; then
		echo -e "\n[!] Starting Bash... "
		clear
		exit 1
	fi
}

main
